jobs:
  - script: >
      folder('test-folder')
  - script: >
      pipelineJob('test-folder/test-job') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('git@git-repo.com:test/test.git')
                  credentials('git-repo-key')
                }
                branch('master')
              }
            }
          }
        }
      }
